"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
test("review form accessibility, safe callback state, account logout and clear conflicts",async()=>{
 const {JSDOM}=await import("jsdom"),html=fs.readFileSync(path.resolve(__dirname,"../review.html"),"utf8"),script=fs.readFileSync(path.resolve(__dirname,"../assets/review-form.js"),"utf8");let authenticated=true,submitBody;
 const dom=new JSDOM(html,{url:"https://synthetic-preview.example.invalid/review.html?auth=success",runScripts:"outside-only"});const w=dom.window,d=w.document;
 w.fetch=async(url,opts={})=>{let data;if(url.endsWith("session"))data={authenticated,csrf:"x".repeat(43),profile:{display_name:"SYNTHETIC Google Professional"}};else if(url.endsWith("submit")){submitBody=JSON.parse(opts.body);return{ok:false,json:async()=>({error:"You have already submitted a review for this professional."})};}else if(url.endsWith("logout")){authenticated=false;data={signed_out:true};}else throw Error("Unexpected external request");return{ok:true,json:async()=>data};};
 w.eval(script);const settle=()=>new Promise(r=>setTimeout(r,20));await settle();assert.equal(d.getElementById("reviewForm").hidden,false);assert.equal(d.querySelector('[name="email"]'),null);assert.equal(d.getElementById("reviewStatus").getAttribute("aria-live"),"polite");
 for(const el of d.querySelectorAll('#reviewForm input:not([name="website"]),#reviewForm select,#reviewForm textarea'))assert(el.labels?.length>0);assert.equal(d.querySelector('[name="website"]').tabIndex,-1);
 const f=d.getElementById("reviewForm");f.elements.display_name.value="SYNTHETIC Display Name";f.elements.rating.value="4";f.elements.comment.value="Synthetic review accessibility fixture.";f.elements.consent.checked=true;f.dispatchEvent(new w.Event("submit",{cancelable:true,bubbles:true}));await settle();assert.equal(d.activeElement,d.getElementById("reviewStatus"));assert.match(d.getElementById("reviewStatus").textContent,/already submitted/);assert.equal(d.getElementById("submitReview").disabled,false);assert.equal(submitBody.email,undefined);assert.equal(submitBody.provider_subject,undefined);assert.equal(submitBody.csrf,"x".repeat(43));d.getElementById("reviewLogout").click();await settle();assert.equal(f.hidden,true);assert.equal(d.getElementById("reviewLogout").hidden,true);assert.equal(d.getElementById("googleReviewLogin").hidden,false);dom.window.close();
 // A fresh fragment must not expose the form for an older cookie's professional.
 const other=new JSDOM(html,{url:"https://synthetic-preview.example.invalid/review.html#"+"a".repeat(43),runScripts:"outside-only"});other.window.fetch=async()=>({ok:true,json:async()=>({authenticated:true,csrf:"x".repeat(43),profile:{display_name:"SYNTHETIC Old Professional"}})});other.window.eval(script);await settle();assert.equal(other.window.location.hash,"");assert.equal(other.window.document.getElementById("reviewForm").hidden,true);assert.equal(other.window.document.getElementById("reviewProfessional").textContent,"");assert.equal(other.window.document.getElementById("googleReviewLogin").disabled,false);other.window.close();
});
