"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const {createLocalPostgres}=require("../scripts/local-postgres"),{createSandbox}=require("../scripts/local-marketplace-sandbox");
test("native PostgreSQL Google reviews: four migrations, independent races and complete reputation",{timeout:120000},async t=>{
 const db=await createLocalPostgres();let s;
 try{s=await createSandbox(0,{db});const owner=s.ids.contractor,actor=s.ids.other;
 const profile={slug:"synthetic-google-native",display_name:"Synthetic native provider",headline:"Synthetic",about:"Synthetic Google review concurrency only.",city:"Riverview",state_code:"FL",zip_code:"33569",radius_miles:25,categories:["Painting"],languages:["English"],social_links:[],portfolio:[],published:true,publish_email:false,publish_phone:false};
 await db.query("select gef_save_public_profile($1,$2::jsonb)",[owner,JSON.stringify(profile)]);
 for(const f of fs.readdirSync(path.resolve(__dirname,"../supabase/migrations")).filter(f=>f.includes("review_")).sort())await db.exec(fs.readFileSync(path.resolve(__dirname,"../supabase/migrations",f),"utf8"));
 const invite=async()=>{const h=crypto.randomBytes(32).toString("hex");await db.query("select gef_create_review_invitation($1,$2)",[owner,h]);return h;};
 const payload=h=>JSON.stringify({token_hash:h,display_name:"Synthetic native reviewer",rating:3,comment:"Synthetic native PostgreSQL concurrent review."});
 async function race(hashes,subject,who=actor){const blocker=await db.connect(),clients=await Promise.all(hashes.map(()=>db.connect()));try{await blocker.query("begin;lock table public.contractor_reviews in share mode");const pids=[];for(const c of clients){await c.query("begin;set local role service_role;set local statement_timeout='15s'");pids.push((await c.query("select pg_backend_pid() pid")).rows[0].pid);}const operations=clients.map((c,i)=>c.query("select gef_submit_authenticated_review($1,$2,$3::jsonb) result",[who,subject,payload(hashes[i])]).then(async r=>{await c.query("commit");return{ok:true,result:r.rows[0].result};},async e=>{await c.query("rollback");return{ok:false,code:e.code};}));let waiting=0;const end=Date.now()+5000;while(Date.now()<end){waiting=Number((await db.query("select count(*) n from pg_stat_activity where pid=any($1::integer[]) and wait_event_type='Lock'",[pids])).rows[0].n);if(waiting===clients.length)break;await new Promise(r=>setTimeout(r,20));}assert.equal(waiting,clients.length);await blocker.query("commit");return await Promise.all(operations);}finally{await blocker.query("rollback");await blocker.end();await Promise.all(clients.map(c=>c.end()));}}
 await t.test("same invitation races consume once and persist one pending review",async()=>{const h=await invite(),r=await race([h,h],"synthetic-native-google");assert.equal(r.filter(x=>x.ok).length,1);assert.equal(Number((await db.query("select count(*) n from contractor_reviews")).rows[0].n),1);});
 await t.test("different invitations and same identity race never create a second review",async()=>{const hashes=[await invite(),await invite()];const who=crypto.randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'synthetic-race@example.invalid',now())",[who]);const r=await race(hashes,"synthetic-new-native-google",who);assert.equal(r.filter(x=>x.ok).length,1);assert(r.filter(x=>!x.ok).every(x=>x.code==="23505"));assert.equal(Number((await db.query("select count(*) n from gef_private.review_invitations where token_hash=any($1::text[]) and used_at is not null",[hashes])).rows[0].n),1);});
 await t.test("Google subject persists uniqueness when the Auth user is recreated",async()=>{const newId=crypto.randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'synthetic-recreated@example.invalid',now())",[newId]);await assert.rejects(db.query("select gef_submit_authenticated_review($1,'synthetic-native-google',$2::jsonb)",[newId,payload(await invite())]),e=>e.code==="23505");});
 await t.test("service role self-review rejection and private RPC access",async()=>{const c=await db.connect();try{await c.query("begin;set local role service_role");await assert.rejects(c.query("select gef_submit_authenticated_review($1,'synthetic-owner',$2::jsonb)",[owner,payload(await invite())]),/Self-review/);await c.query("rollback");for(const role of ["anon","authenticated"]){const row=(await db.query("select has_function_privilege($1,'public.gef_submit_authenticated_review(uuid,text,jsonb)','EXECUTE') x",[role])).rows[0];assert.equal(row.x,false);}}finally{await c.end();}});
 await t.test("approved summary uses all 101 reviews, not just displayed 100",async()=>{const rows=[];for(let i=0;i<101;i++){const user=crypto.randomUUID(),inv=crypto.randomUUID(),review=crypto.randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[user,"synthetic-aggregate-"+i+"@example.invalid"]);await db.query("insert into gef_private.review_invitations(id,contractor_id,token_hash,source,expires_at,used_at) values($1,$2,$3,'external',now()+interval '1 day',now())",[inv,owner,crypto.randomBytes(32).toString("hex")]);await db.query("insert into contractor_reviews(id,contractor_id,invitation_id,display_name,rating,comment,source,status) values($1,$2,$3,'Synthetic aggregate',$4,'Synthetic aggregate reputation fixture.','external','approved')",[review,owner,inv,i===100?5:3]);await db.query("insert into gef_private.review_authenticated_identities(review_id,contractor_id,reviewer_user_id,provider,provider_subject) values($1,$2,$3,'google',$4)",[review,owner,user,"synthetic-aggregate-"+i]);rows.push(review);}const p=(await db.query("select gef_public_profile('synthetic-google-native') r")).rows[0].r;assert.equal(p.reviews.length,100);assert.equal(p.review_summary.approved_count,101);assert(Math.abs(Number(p.review_summary.average_rating)-305/101)<1e-10);assert(!/provider_subject|reviewer_user_id|identity_hash/.test(JSON.stringify(p)));});
 }finally{if(s)await s.close();else await db.close();}
});
